[package]
name = "sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
bitfield-struct   = "0.12.1"
concat-idents     = "1.1.5"
num               = {version = "0.4.3", default-features = false}
simple-bits       = "1.0.1"
static_assertions = "1.1.0"